version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: increase
    registries: "*"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 20